import React, { useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { FileText, Download, Loader2 } from 'lucide-react';

// Extend window for html2pdf
declare global {
  interface Window {
    html2pdf: any;
  }
}

interface MarkdownPreviewProps {
  content: string;
  isLoading: boolean;
}

const MarkdownPreview: React.FC<MarkdownPreviewProps> = ({ content, isLoading }) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = () => {
    if (!contentRef.current || !window.html2pdf) return;

    const element = contentRef.current;
    const opt = {
      margin:       [10, 10, 10, 10], // top, left, bottom, right
      filename:     'tutorial-guide.pdf',
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    // Use html2pdf library to save
    window.html2pdf().set(opt).from(element).save();
  };

  if (isLoading) {
    return (
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-12 flex flex-col items-center justify-center h-full min-h-[400px]">
        <Loader2 className="w-12 h-12 text-indigo-600 animate-spin mb-4" />
        <h3 className="text-xl font-medium text-slate-800">AI 正在撰写教程...</h3>
        <p className="text-slate-500 mt-2">这可能需要几秒钟，请稍候。</p>
      </div>
    );
  }

  if (!content) {
    return (
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-12 flex flex-col items-center justify-center h-full min-h-[400px] text-center">
        <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
          <FileText className="w-8 h-8 text-slate-400" />
        </div>
        <h3 className="text-lg font-medium text-slate-700">等待生成</h3>
        <p className="text-slate-500 mt-2 max-w-sm">
          在左侧输入视频文字稿并点击“开始生成”，AI 将为您整理出完美的步骤文档。
        </p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl shadow-sm border border-slate-200 flex flex-col h-full overflow-hidden">
      {/* Header / Toolbar */}
      <div className="border-b border-slate-100 p-4 bg-slate-50 flex justify-between items-center">
        <h3 className="font-semibold text-slate-700 flex items-center gap-2">
          <FileText className="w-4 h-4" />
          教程预览
        </h3>
        <button
          onClick={handleDownloadPDF}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm"
        >
          <Download className="w-4 h-4" />
          下载 PDF
        </button>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-auto p-8 bg-white" >
        <div className="prose prose-slate prose-indigo max-w-none print:prose-sm" id="markdown-content" ref={contentRef}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {content}
            </ReactMarkdown>
        </div>
      </div>
      
      {/* Footer Info */}
      <div className="bg-slate-50 p-2 text-center text-xs text-slate-400 border-t border-slate-100">
        Generated by AI • PDF Export Available
      </div>
    </div>
  );
};

export default MarkdownPreview;
